spring:
  vectorstore:
    datasource:
      url: jdbc:postgresql://190.160.13.13:20039/dataagentdb
      username: dataagent
      password: a123456.
      driver-class-name: org.postgresql.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  ai:
    vectorstore:
      type: pgvector
      pgvector:
        schema-name: dataagent
        table-name: vector_store
        schema-validation: false
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10000
