server {
location ~ ^/(nl2sql/api/stream/search|nl2sql/api/agent/[^/]+/sessions/stream)/?$ {
    add_header Content-Type text/event-stream;
    add_header Cache-Control no-cache;
    add_header Connection keep-alive;
    proxy_http_version 1.1;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Connection "";

    proxy_buffering off;
    proxy_cache off;
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 3600s;
    tcp_nodelay on;
    proxy_redirect off;
    proxy_pass https://190.160.13.13:$server_port;
    proxy_ssl_verify off;
    proxy_ssl_session_reuse off;
    gzip off;
  }
}